version: '3.8'

services:
  app:
    build:
      context: flaskr
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env

  db:
    image: postgres:12.3
    env_file:
      - .env
    volumes:
      - /data:/var/lib/postgresql/data